title: Math Every Day
description: A detailed guide to Game theory
show_downloads: false
# Remove or replace with your own Tracking ID if you actually want analytics:
# google_analytics: UA‑XXXXXXX‑X

# Pull in Cayman from GitHub Pages’ supported themes repo:
remote_theme: pages-themes/cayman@v0.2.0

# Enable the remote-theme plugin so `remote_theme` works:
plugins:
  - jekyll-remote-theme

kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts: {}    # ← give it an empty hash instead of nil


sass:
  style: compressed

include:
  - assets/css/style.scss
