title: Math blog
description: Game theory
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
# Tell Pages to fetch Cayman remotely (with a version tag)
remote_theme: pages-themes/cayman@v0.2.0

# Enable the remote-theme plugin
plugins:
  - jekyll-remote-theme